### ISSUE TITLE
Alfred Workflow Incomptaible With Alfred v3.8.5 [970]

### ISSUE THREAD

**Issue by thejohnnyxu** [kevinjalbert/notion-toolbox#11]
Hey -- Love your work.

Got the scripts working with some tweaking -- but I was very curious how you rigged up the Alfred workflow. 

Let me know what version Alfred your workflow is compatible with -- Would love to test out this integration.

**Comment by kevinjalbert** [comment]
Glad you are liking the work 😄.

> I was very curious how you rigged up the Alfred workflow.

As I mentioned in the Readme's [Get the Workflow in Alfred](https://github.com/kevinjalbert/alfred-notion#get-the-workflow-in-alfred) section you basically dump the repository into your blank workflow. I'm not sure if that was what you were asking for?

> Let me know what version Alfred your workflow is compatible with

As I mentioned in the [Readme's Setup](https://github.com/kevinjalbert/alfred-notion#setup), this workflow requires Alfred 3+. I'm currently running on the latest Alfred 4 with no issues as well.

**Comment by kevinjalbert** [comment]
@thejohnnyxu just noticed the title of this lol (Alfred Workflow Incompatible With Alfred v3.8.5 [970]).

What is the situation that you are seeing? Like I mentioned I'm using version 4, so I'm not 100% sure what might be the issues. I _don't think_ I'm using anything specific to v4 though, although I could be wrong.

**Comment by Bisgates** [comment]
It shows "Workflow incompatible", I also use v3.8.5. Hope support with v3, would be very helpful :)

**Comment by kevinjalbert** [comment]
To be honest I don't really have the bandwidth to investigate how to make this work with 3.x, as I've moved on to using Alfred 4.x.

I'll be making a change to the README to mention that this is for Alfred 4.x until someone can confirm it works in 3.x again.

Sorry about this, as this is likely not the resolution you were hoping for.
