### ISSUE TITLE
Issue when updating local tags

### ISSUE THREAD

**Issue by carlosflorencio** [kevinjalbert/notion-toolbox#17]
Hi,

I'm having an issue when trying to fetch the remote tags:
```
❯ python3 src/update_tags.py
Traceback (most recent call last):
  File "src/update_tags.py", line 12, in <module>
    results = database.default_query().execute()
  File "/usr/local/lib/python3.7/site-packages/notion/collection.py", line 223, in default_query
    return self.build_query(**self.get("query2", {}))
  File "/usr/local/lib/python3.7/site-packages/notion/collection.py", line 219, in build_query
    collection=self.collection, collection_view=self, **kwargs
  File "/usr/local/lib/python3.7/site-packages/notion/collection.py", line 301, in __init__
    assert not (aggregate and aggregations), "Use only one of `aggregate` or `aggregations` (old vs new format)"
AssertionError: Use only one of `aggregate` or `aggregations` (old vs new format)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/update_tags.py", line 39, in <module>
    sys.stderr.write(e)
TypeError: write() argument must be str, not AssertionError
zsh: exit 1     python3 src/update_tags.py
```

Since the query is `"query2"` it must be using your notion-py repo which contains this patch, did the notion API change in the meantime?

Thanks!

**Comment by kevinjalbert** [comment]
@carlosflorencio I can confirm that this is an issue even with the patch that was applied. I guess I never noticed it as I haven't been modifying my tags lately.

> AssertionError: Use only one of `aggregate` or `aggregations` (old vs new format)

This does seem to be a case of the new vs. old API situation.

-----

I haven't the time as of late to dig into this unfortunately.

As a related note, I've been playing around with idea of abandoning the global tags approach and just using a multi-select field. If I do go that route, it would simplify a lot of the tagging code. I'm _pretty_ sure I'll go this route, but will have to give it a bit more thought.

**Comment by carlosflorencio** [comment]
Thanks @kevinjalbert, I'll hardcode the tags in the meantime. 👍

**Comment by carlosflorencio** [comment]
The search functionality is returning the same error FYI.
