### ISSUE TITLE
How can I use the notion toolbox in my alfred?

### ISSUE THREAD

**Issue by scq000** [kevinjalbert/notion-toolbox#36]
Could you give us more detailed instructions to use it? Thank you.

**Comment by kevinjalbert** [comment]
The Alfred workflow related stuff has been deprecated as I've moved forward and haven't reimplemented it using the new format. The README on the `master` branch mentioned this and links to a specific Git SHA that has the older stuff you are likely looking for.

https://github.com/kevinjalbert/notion-toolbox/tree/63d8bf16670b44ec355132d5f251e0728fc5cd78/alfred

This should cover the instructions on how to get it working, granted you'll have to be using that specific SHA on checkout.

**Comment by m0rtyn** [comment]
Hi, i'm took repo with Alfred workflow and reuse it for myself.
New repo with Alfred Workflow here:
https://github.com/m0rtyn/alfred-fast-note-to-notion
