### ISSUE TITLE
shortcut-append.jpeg & "Error: The data couldn't be read because it isn't in the correct format."

### ISSUE THREAD

**Issue by florence26** [kevinjalbert/notion-toolbox#40]
Hello!

Apologies if this is a very simple question.

On the shortcut-append.jpeg, how do you configure the Shortcut Input for the first "if" statement? When I create a new ios shortcut and use Shortcut Input as an input, it requires me to receive an input from a certain location. I can't find a method to connect Scriptable outputs as an input to the ios shortcut.
![notion__](https://github.com/kevinjalbert/notion-toolbox/assets/32259316/2c4919d2-8dc3-4d7a-b3a2-7c4d09c8820c)

I haven't configured the shortcut-append, shortcut-delete and shortcut-refresh shortcuts yet, but after completing all the steps prior to that, I'm getting this error on my widget:
![notion_](https://github.com/kevinjalbert/notion-toolbox/assets/32259316/f1cd0a6c-e046-44eb-962b-6883e5499d41)

Any help with these two issues will be really appreciated!

Thank you for the script!!

**Comment by kevinjalbert** [comment]
Looks like Shortcuts has changes in recent iOS version. This is what I have for mine right now:

![image](https://github.com/kevinjalbert/notion-toolbox/assets/574871/465717bb-608b-4fd9-9987-e7ae1b36f57f)

Looks like it just changed to 'everything'.

---

As for the other part, the issue would be that you'd need to have the server component running somewhere – to which my instance is likely not running any more (I stopped using notion a while back).

There is this PR (https://github.com/kevinjalbert/notion-toolbox/pull/37), that I haven't fully vetted, but it would be leveraging the official API (as there wasn't an official one when I built this). That would be your best bet moving forward! Good luck and let me know if that PR worked out for you.

---

Closing this issue out, but do let me know if that PR's branch works out, and I'll just merge it in and make it the official way forward with this repo.

**Comment by florence26** [comment]
Thanks for the info! PR #37 works as a general widget and the new task function also works fine. However, the refresh functionality and the ability to mark tasks as completed aren't. Been trying to debug it but haven't found a solution yet.
